In [6]:
# With help from tutorial @ Ken Jee Youtube: https://www.youtube.com/watch?v=7O4dpR9QMIM&t=308s&ab_channel=KenJee

In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [8]:
# load in cleaned csv
df = pd.read_csv('cleaned_nba_2020.csv')
df.head()

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,3P,...,FTA,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,Steven Adams,C,26,OKC,63,63,26.7,4.5,7.6,0.0,...,3.2,3.3,6.0,9.3,2.3,0.8,1.1,1.5,1.9,10.9
1,Bam Adebayo,PF,22,MIA,72,72,33.6,6.1,11.0,0.0,...,5.3,2.4,7.8,10.2,5.1,1.1,1.3,2.8,2.5,15.9
2,LaMarcus Aldridge,C,34,SAS,53,53,33.1,7.4,15.0,1.2,...,3.6,1.9,5.5,7.4,2.4,0.7,1.6,1.4,2.4,18.9
3,Kyle Alexander,C,23,MIA,2,0,6.5,0.5,1.0,0.0,...,0.0,1.0,0.5,1.5,0.0,0.0,0.0,0.5,0.5,1.0
4,Nickeil Alexander-Walker,SG,21,NOP,47,1,12.6,2.1,5.7,1.0,...,0.8,0.2,1.6,1.8,1.9,0.4,0.2,1.1,1.2,5.7

In [11]:
# choose relevant columns 
# as most the data revolves 
df.columns

Index(['Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG', 'FGA', '3P', '3PA',
       '2P', '2PA', 'FT', 'FTA', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK',
       'TOV', 'PF', 'PTS'],
      dtype='object')

In [13]:
# We want columns that will help determine the player's PTS
df_model = df[['Player', 'Pos', 'Age', 'Tm', 'MP', 'FG', 'FGA', '3P', '3PA', '2P', '2PA', 'FT', 'FTA']]
df_model.head()

,Player,Pos,Age,Tm,MP,FG,FGA,3P,3PA,2P,2PA,FT,FTA
0,Steven Adams,C,26,OKC,26.7,4.5,7.6,0.0,0.0,4.5,7.5,1.9,3.2
1,Bam Adebayo,PF,22,MIA,33.6,6.1,11.0,0.0,0.2,6.1,10.8,3.7,5.3
2,LaMarcus Aldridge,C,34,SAS,33.1,7.4,15.0,1.2,3.0,6.2,12.0,3.0,3.6
3,Kyle Alexander,C,23,MIA,6.5,0.5,1.0,0.0,0.0,0.5,1.0,0.0,0.0
4,Nickeil Alexander-Walker,SG,21,NOP,12.6,2.1,5.7,1.0,2.8,1.1,2.8,0.5,0.8

In [21]:
# get dummy data
# used in regression analysis to represent subgroups of the sample in the study
# categorical data
df_dum = pd.get_dummies(df_model)
df_dum.head()

,Age,MP,FG,FGA,3P,3PA,2P,2PA,FT,FTA,...,Tm_ORL,Tm_PHI,Tm_PHO,Tm_POR,Tm_SAC,Tm_SAS,Tm_TOR,Tm_TOT,Tm_UTA,Tm_WAS
0,26,26.7,4.5,7.6,0.0,0.0,4.5,7.5,1.9,3.2,...,0,0,0,0,0,0,0,0,0,0
1,22,33.6,6.1,11.0,0.0,0.2,6.1,10.8,3.7,5.3,...,0,0,0,0,0,0,0,0,0,0
2,34,33.1,7.4,15.0,1.2,3.0,6.2,12.0,3.0,3.6,...,0,0,0,0,0,1,0,0,0,0
3,23,6.5,0.5,1.0,0.0,0.0,0.5,1.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
4,21,12.6,2.1,5.7,1.0,2.8,1.1,2.8,0.5,0.8,...,0,0,0,0,0,0,0,0,0,0

In [28]:
# train test split
X = df_dum.drop('PTS', axis=1)
y = df_dum.PTS.values
X_train, X_test, y_train, t_test = train_test_split(X, y, test_size=0.2, random_state=42)

KeyError: "['PTS'] not found in axis"